apiVersion: apps/v1
kind: Deployment
metadata:
  name: partyauthentication-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: partyauthentication-service
  template:
    metadata:
      labels:
        app: partyauthentication-service
    spec:
      containers:
      - name: partyauthentication-service
        image: imagen-partyauthentication:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: partyauthentication-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: partyauthentication-service